kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "nitter.name" . }}-config
  labels:
    {{- include "nitter.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "config/*.conf").AsConfig . | indent 2 }}
