kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "breezewiki.name" . }}-config
  labels:
    {{- include "breezewiki.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "config/*").AsConfig . | indent 2 }}
